services:
  - type: web
    name: iuep-connect
    runtime: docker
    region: singapore
    plan: free
    branch: main
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health
